# Generated by Django 2.0.5 on 2018-05-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificio', to='edificio.Edificio')),
            ],
        ),
    ]
