# Generated by Django 2.0.5 on 2018-05-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '__first__'),
        ('cliente', '0004_auto_20180513_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='edificio',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='departamento.Departamento'),
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Edificio',
        ),
    ]
